name: Build and Push to ECR and GHCR

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # OIDC token for AWS
  contents: read
  packages: write  # Needed for GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      ##  AWS ECR AUTHENTICATION
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::605134474431:role/GitHubActionRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## GHCR AUTHENTICATION
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # Create a PAT for GHCR

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      ##  Build & Push Backend Image (ECR + GHCR)
      - name: Build and Push Backend
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_IMAGE="$ECR_REGISTRY/backend:latest"
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/backend:latest"

          docker build -t $ECR_IMAGE -t $GHCR_IMAGE ./backend
          docker push $ECR_IMAGE
          docker push $GHCR_IMAGE

          echo " Backend pushed to: $ECR_IMAGE"
          echo " Backend pushed to: $GHCR_IMAGE"

      ## Build & Push Frontend Image (ECR + GHCR)
      - name: Build and Push Frontend
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_IMAGE="$ECR_REGISTRY/frontend:latest"
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/frontend:latest"

          docker build -t $ECR_IMAGE -t $GHCR_IMAGE ./frontend
          docker push $ECR_IMAGE
          docker push $GHCR_IMAGE

          echo " Frontend pushed to: $ECR_IMAGE"
          echo " Frontend pushed to: $GHCR_IMAGE"

          